# Generated by Django 4.0.3 on 2022-04-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_alter_cache_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='r_1',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_10',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_2',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_3',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_4',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_5',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_6',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_7',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_8',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='r_9',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
